version: '2'
services:
 
  redis1:
    image: redis:3.2.5-alpine
    container_name: redis1
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
 
  redis2:
    image: redis:3.2.5-alpine
    container_name: redis2
    command: redis-server --slaveof redis1 6379
    links:
      - redis1
    volumes:
      - "./.data:/data"

  redis3:
    image: redis:3.2.5-alpine
    container_name: redis3
    command: redis-server --slaveof redis1 6379
    links:
      - redis1
    volumes:
      - "./.data:/data"
     
  redis-sentinel:
    container_name: redis-sentinel1
    build: 
      context: ./redis-sentinel
    links:
      - redis1
 
  redis-sentinel2:
    container_name: redis-sentinel2
    build: 
      context: ./redis-sentinel
    links:
      - redis1
 
  redis-sentinel3:
    container_name: redis-sentinel3
    build: 
      context: ./redis-sentinel
    links:
      - redis1
